---
title: "Research"
engine: knitr
---

Here you find all the references and links to my academic research, including both peer-reviewed and non-peer-reviewed publications.

## Work in Progress

---------

### Facing the Populists: The Effect of Populist Challengers on Mainstream Parties’ Welfare State Positions

*Draft paper available at:* [SSRN](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4643366)

**Abstract**: This article investigates the effect of populists’ electoral success on European mainstream parties’ positions about the economic dimension and the social inclusiveness of the welfare state. Combining data from party manifestos with a Regression Discontinuity Design, this article finds that a populist party obtaining representation constitutes a supply-side mechanism inducing an adjustment over mainstream parties’ positions, independently from public opinion changes. After competing with a populist party, mainstream parties shift their positions in favor of a smaller and more exclusionary welfare state. In terms of programmatic distances, mainstream parties tend to converge with the populists on both the cultural and economic dimension of the welfare state issue.

## Peer-Reviewed Publications

--------

### Will the Real Populists Please Stand Up? A Machine Learning Index of Party Populism
*with Martin Rode & Ignacio Rodriguez Carreño* - European Journal of Political Economy (2024) - [Link](https://www.sciencedirect.com/science/article/pii/S0176268024000314?via%3Dihub)

*Data visualization web-app* [Link](https://acelico.shinyapps.io/rfpopi_app/)

**Abstract**: The existing literature on populism has seen numerous attempts to empirically quantify this somewhat ambiguous concept. Despite notable advances, continuous measures of populism with a clear theoretical background and a considerable coverage are still hard to come by. This paper proposes a novel approach to measuring party populism by combining several different expert-surveys via supervised machine learning techniques. Employing the random forest regression algorithm, we greatly expand the geographical and temporal coverage of two well-known populism indicators, which are based on the discursive and the ideational approach, respectively. The resulting multidimensional measures capture party-level populism on a continuous 0–10 scale, covering 1920 parties in 169 countries from 1970 to 2019. Our measures accurately replicate both definitions of populism, although the indicators may be more suitable for predicting populist outcomes in Western countries, as compared to non-Western ones.

### Can We All Be Denmark? The Role of Civic Attitudes in Welfare State Reforms
*with Martin Rode* - Empirica (2023) - [Link](https://link.springer.com/article/10.1007/s10663-023-09588-7)

**Abstract**: Research has demonstrated the economic effectiveness of welfare state reforms that follow the Danish flexicurity model, broadly specifying the combination of highly flexible labor market policies and generous protection schemes. Notwithstanding, it has also been argued that large and generous welfare states may erode civic attitudes, defined here as people’s willingness to cheat on taxes and claim transfers to which they are not entitled. Combining data from all available waves of the World Values Survey and the European Values Study with a self-constructed flexicurity index, this paper finds that welfare state reforms involving a combination of higher benefits, lower labor market regulations, and active labor market policies are not significantly associated with an erosion of civic attitudes.

## Other Publications

----

### Populism, Majority Rule, and Economic Freedom 
*with Martin Rode* - Economic Freedom of the World: 2023 Annual Report (Fraser Institute, 2023) - [Link](https://www.fraserinstitute.org/sites/default/files/populism-majority-rule-and-economic-freedom-ch3.pdf)

**Executive Summary**: In this chapter from the forthcoming Economic Freedom of the World: 2023 Annual Report, Andrea Celico and Martin Rode of the Universidad de Navarra investigate the relationship between populism and economic freedom, and also consider the potentially mediating roles of institutional constraints and government ideology. Controlling for other determinants, they find that populism in government is significantly associated with reductions in economic freedom for a large sample of democratic countries. They also find that in OECD countries, the negative association between populism and economic freedom seems to be mediated to a substantial degree by political constraints and political ideology. It is possible that institutional guardrails, which are often absent in many non-OECD countries, check the power of populist governments.
